version: 0.1

phases:
  install:
    commands:
      - echo Entering install phase...
      - echo Nothing to do now
  build:
    commands:
      - gradle build
artifacts:
  type: zip
  files:
    - 'build/libs/*.war'